
- name: "Check if galera is config exists"
  ansible.builtin.stat:
    path: /var/lib/mysql/grastate.dat
  register: grastate

- name: "Set root .my.cnf file"
  ansible.builtin.template:
    src: root/dot.my.cnf.j2
    dest: /root/.my.cnf
    mode: "0600"

- name: "Make mysql_secure_install manually"
  when: not grastate.stat.exists
  block:
    - name: "Switch to socket auth mariadb"
      ansible.builtin.template:
        src: etc/mysql/my.cnf.j2
        dest: /etc/mysql/my.cnf
        mode: "0644"

    - name: Update MariaDB root password
      community.mysql.mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ galera_mysql_root_password }}"
      with_items: []
      # - 127.0.0.1
      # - ::1
      # - localhost

    - name: Delete anonymous MySQL user
      community.mysql.mysql_user:
        name: ""
        host: "{{ item }}"
        state: absent
      with_items:
        - localhost
        - "{{ ansible_nodename }}"

    - name: Delete Hostname based MySQL user
      community.mysql.mysql_user:
        name: root
        host: "{{ ansible_nodename }}"
        state: absent

    - name: Remove MySQL test database
      community.mysql.mysql_db:
        name: test
        state: absent

- name: "Push 60-galera.cnf to /etc/mysql/mariadb.conf.d/"
  ansible.builtin.template:
    src: etc/mysql/mariadb.conf.d/60-galera.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/60-galera.cnf
    mode: "0644"