
- name: "Update package list"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: "Install requirements"
  ansible.builtin.apt:
    package:
      - "software-properties-common"
      - "mariadb-client"
      - "mariadb-server"
      - "galera-4"
      - "python3-pymysql"
    state: "present"
