---
# tasks file for galera-cluster

- name: "Install"
  ansible.builtin.include_tasks: "install.yml"

- name: "Configure"
  ansible.builtin.include_tasks: "configure.yml"

- name: "Bootstrap"
  ansible.builtin.include_tasks: "bootstrap.yml"

- name: "Database"
  ansible.builtin.include_tasks: "mysql_databases.yml"
 

- name: "Users"
  ansible.builtin.include_tasks: "mysql_users.yml"