- name: create MySQL users
  mysql_user:
    host: "{{ item.1 }}"
    login_unix_socket: "{{ mariadb_login_unix_socket | default(omit) }}"
    name: "{{ item.0.name }}"
    password: "{{ item.0.password | default(omit) }}"
    plugin: "{{ item.0.plugin | default(omit) }}"
    plugin_auth_string: "{{ item.0.plugin_auth_string | default(omit) }}"
    plugin_hash_string: "{{ item.0.plugin_hash_string | default(omit) }}"
    tls_requires: "{{ item.0.tls_requires | default(omit) }}"
    priv: "{{ item.0.priv | default('*.*:USAGE') }}"
    state: "{{ item.0.state | default('present') }}"
  delegate_to: "{{ galera_bootstrap_node }}"
  run_once: true
  no_log: true
  with_subelements:
    - "{{ galera_users }}"
    - hosts